elastic/elastic-agent-system-metrics

- report/metrics_file_descriptors.go
- report/metrics_file_descriptors_stub.go
- report/metrics_handles.go
- report/metrics_handles_stub.go
Two platform specific metric reporter were missing. These two reporters are required for Agent and Fleet server.
> Move missing platform specific metrics

- metric/system/filesystem/filesystem_test.go
- metric/system/numcpu/numcpu_test.go
This fixes some issues I noticed with the CI on https://github.com/elastic/elastic-agent-system-metrics/pull/7
Notably, this filters a filesystem type that doesn't work on darwin, and clarifies a test log output.
> fix issues with upcoming CI support

- go.mod
- go.sum
- report/metrics_common.go
- report/setup.go
- report/setup_other.go
This PR moves the metrics setup from Beats to a common place. Previously the reporter functions were used in Agent to provide some flexibility. But it turns out that flexibility is not needed, and avoiding CGO is more important.
This PR is also required by fleet-server: https://github.com/elastic/fleet-server/pull/1351
> Move metrics setup to this repo

- report/setup_other.go
Fix the incorrect package name so the module can be used on multiple flatforms:
```
found packages report (metrics_common.go) and metrics (setup_other.go) in /go/pkg/mod/github.com/elastic/elastic-agent-system-metrics@v0.2.0/report
```
> Fix package name for `setup` for other platforms

- metric/system/filesystem/filesystem.go
- metric/system/filesystem/filesystem_darwin.go
- metric/system/filesystem/filesystem_test.go
- metric/system/filesystem/filesystem_unix.go
- metric/system/filesystem/filesystem_unix_common.go
- metric/system/filesystem/filesystem_windows.go
Due to some miscommunication over what was going where, #7 removed the PR that added the new refactored filesystem code, so this adds it back in.
> Revert changes that removed filesystem code

- metric/system/process/process.go
- metric/system/process/process_common.go
- metric/system/process/process_darwin.go
- report/metrics_file_descriptors_stub.go
With the refactoring of `SetupLinuxBSDFDMetrics`, `process.Stats` got imported on darwin. However, to use `process` package on darwin CGO is required. I have separated the process package so `process.Stats` can be imported on `darwin` without CGO. This way, the `SetupLinuxBSDFDMetrics` stub can be called when necessary.
Required by https://github.com/elastic/fleet-server/pull/1351
> Fix build tags for `darwin` after refactoring of metrics handles

- .github/CODEOWNERS
This will auto-assign reviewers like in our other repositories.
> Add agent data plane team as code owners.

- .golangci.yml
- metric/system/cgroup/cgv2/memory.go
- metric/system/filesystem/filesystem.go
- metric/system/process/helpers.go
- metric/system/process/process.go
- metric/system/process/process_test.go
Along with the fix I have increased the threshold for `goconst` linter to 5.
> Pick process list filtering fix from elastic/beats#31595

- CHANGELOG.md
This PR adds a CHANGELOG.md file, so we can track the changes in the repo. This commit also prepares for the new v0.3.0 release of the module.
> Add CHANGELOG.md to repo

- CHANGELOG.md
- metric/system/process/process_common.go
This PR adds `openbsd` and `freebsd` to the list of build tags protecting `process_common.go` file.
Without this change libbeat cannot be crosscompiled on openbsd and freebsd:
```
2 errors occurred:
--> openbsd/amd64 error: exit status 2
Stderr: # github.com/elastic/elastic-agent-system-metrics/metric/system/process
../../../../../pkg/mod/github.com/elastic/elastic-agent-system-metrics@v0.3.0/metric/system/process/process_types.go:32:11: undefined: PidState
../../../../../pkg/mod/github.com/elastic/elastic-agent-system-metrics@v0.3.0/metric/system/process/process_types.go:161:10: undefined: PidState
--> netbsd/amd64 error: exit status 2
Stderr: # github.com/elastic/elastic-agent-system-metrics/metric/system/process
../../../../../pkg/mod/github.com/elastic/elastic-agent-system-metrics@v0.3 …
```
> Add `netbsd` an `openbsd` to build tags of `process_common.go`

- CHANGELOG.md
- metric/system/process/process_common.go
This is a fix for https://github.com/elastic/beats/issues/20961
It differentiates between actual idle states and an uninterruptible disk sleep.
These are two different states, but we've always reported both as `idle`, for whatever reason.
> Add uninterruptible disk sleep to system/process metrics

- .golangci.yml
- dev-tools/templates/.golangci.yml
I recently went through and disabled the most commonly ignored linters in beats: https://github.com/elastic/beats/pull/31683
This PR updates the lint configuration used in this repository with those that were removed in beats. Let's keep the lint rules consistent across our repositories.
> Synchronize lint rules across repositories

- report/setup.go
Fix for a bug reported by @cmacknz where the migration process of metrics from `libbeat` to here also changed the location of the `handles` monitoring metrics. This changes it back from `"system"` to `"beat"`. We don't have any tests here, so a tad hard to validate this until it makes its way up to the beats repo again.
> Move registry used by handles processor

- CHANGELOG.md
- metric/system/process/helpers.go
- metric/system/process/process.go
- metric/system/process/process_test.go
- metric/system/process/process_types.go
This fixes three issues:
- Gives `CPUTotals` an `IsZero` method, so we don't report `{}` fields during certain events
- Fills out the `Value` field for `GetSelf()`, which is used by beats self-monitoring, and apparently that value is used by the `elastic_agent` dashboard.
- Make processes fetched with `GetSelf()` persist across calls
> Add IsZero to CPU Totals, report value for monitoring

- CHANGELOG.md
- metric/system/process/process.go
- metric/system/process/process_common.go
- metric/system/process/process_linux_common.go
- metric/system/process/process_test.go
- report/metrics_report_test.go
This fixes https://github.com/elastic/beats/issues/32467
This code originates from metricbeat, which never worried too much about threadsafety, since a single metricset just lives in its own thread. However, the code has carried over to beat's self-monitoring in `report/`. A previous PR fixed a bug where `GetSelf()` would not calculate percentages, as it never accessed its own internal map of processes that it uses to calculate percentages. However, `setup.go` was creating a single instance of the process `Stat` struct to send to multiple function callbacks in the monitoring, hence a concurrent map access. 
Wanted to get this PR up fast, still testing on non-linux systems.
Potential concurrent hashmap access issue.
> fix thread safety in process code

- .ci/Jenkinsfile
Run build/test in the CI on `macos m1` workers on `merge-commits` or `/test all` if a GitHub command
More test coverage
> ci: enable orka m1 builds

- metric/system/process/process.go
- metric/system/process/process_common.go
So, this is to help along the CI in https://github.com/elastic/beats/pull/33169
Specifically, the github CI has cgo disabled, and the main `process.go` file has a build requirement of `darwin & cgo`
So, this moves the two exported "helper" functions to `process_common.go` as they don't actually need any build constraints, and they don't really fit with everything else in the `process.go` file.
I'm not 100% sure _why_ the `process.go` file has a build constraint on darwin and cgo, but considering that this is part of a bugfix that's get backported post-FF, I'm reluctant to go tinkering around in build logic.
> Move exported helpers to process_common.go file

- metric/system/process/process.go
- metric/system/process/process_common.go
This reverts commit eb54ad9a98dcd27da23331d41910a5c738edb303.
That change was made while fighting with the CI issues in https://github.com/elastic/beats/pull/33169
We eventually made a different (admittedly still kinda ugly) workaround, rendering this change unnecessary, and I think it may cause issues on Darwin.
> Revert "move exported helpers to _common.go file"

- metric/system/network/helpers.go
- metric/system/network/helpers_test.go
- metric/system/process/process.go
- metric/system/process/process_common.go
- metric/system/process/process_test.go
- metric/system/process/process_types.go
This is one half of https://github.com/elastic/beats/issues/7461
This adds per-process network stats on linux, taken from `/proc/PID/net/netstat` and `/proc/PID/net/SNMP`. 
These metrics are the same kind used in the docker module for reporting docker network summary data.
This also includes a filter function, since all the data in the aforementioned two procfs files includes a prodigious amount of metrics.
There's a notable limitation here, which is that the procfs handler we're importing from `go-sysinfo` can't handle an alternate procfs.
This is an asked-for feature.
> Add per-process network stats

- CHANGELOG.md
- metric/system/cgroup/cgv2/io_helper_linux.go
On mips platforms, Stat_t.Rdev is uint32 (for example https://cs.opensource.google/go/go/+/refs/tags/go1.20.1:src/syscall/ztypes_linux_mips64.go;l=107) resulting in a type error. So explicitly convert to uint64.
```
$ grep 'Rdev\s*uint32' *.go
syscall_linux_mips64x.go:	Rdev       uint32
ztypes_dragonfly_amd64.go:	Rdev     uint32
ztypes_freebsd_386.go:	Rdev          uint32
ztypes_freebsd_amd64.go:	Rdev          uint32
ztypes_freebsd_arm.go:	Rdev          uint32
ztypes_freebsd_arm64.go:	Rdev          uint32
ztypes_linux_mips.go:	Rdev    uint32
ztypes_linux_mips64.go:	Rdev    uint32
ztypes_linux_mips64le.go:	Rdev    uint32
ztypes_linux_mipsle.go:	Rdev    uint32
```
Please inform on need for backport.
The current code will not build on mips platforms.
-
> metric/system/cgroup/cgv2: ensure Rdev is correct width

- metric/system/process/process_linux_common.go
- metric/system/process/process_linux_test.go
- metric/system/process/process_test.go
Part of https://github.com/elastic/elastic-agent-system-metrics/issues/72
This fixes a regression where previous versions of the system/process code on linux that would ignore certain permissions errors that can arise when we try to fetch metrics for a process that belongs to a different user. Currently, system/process will skip over those PIDs entirely. This restores the old behavior, where we merely skip over the metrics we don't have access to.
This is a regression.
> Linux process permission fix

- metric/system/host/host.go
Fixes a small error made in #75.  Instead of having the `host.MapHostInfo` function report the FDQN via the `host.hostname` field, it reports it via a new field, `host.name`.
As decided in https://github.com/elastic/beats/issues/1070#issuecomment-1323387491, we want `host.name` to report the FQDN (when the FQDN is requested) and `host.hostname` to continue reporting the short hostname as before.
- Follow up to #75
> Return FQDN in new field

- go.mod
- go.sum
- metric/system/host/host.go
- metric/system/host/host_test.go
Updates the `host.MapHostInfo` and `host.ReportInfo` functions with [changes made to the `go-sysinfo` API](https://github.com/elastic/go-sysinfo/pull/159).
Needed by https://github.com/elastic/beats/pull/34946, specifically:
* https://github.com/elastic/beats/pull/34946/files#r1150621508, and
* https://github.com/elastic/beats/pull/34946/files#r1150616166
- Follow up to https://github.com/elastic/elastic-agent-system-metrics/pull/75 and https://github.com/elastic/elastic-agent-system-metrics/pull/76
> Update host functions with `go-sysinfo` API changes

- report/metrics_common.go
- report/setup.go
When I did https://github.com/elastic/elastic-agent-system-metrics/pull/80, I didn't notice that I put the code in a file with a cgo build constraint, and proceeded to not notice until I ran `mage package` on something else. None of this code actually requires cgo, so place it in `metrics_common.go`
This code doesn't require cgo.
> Move SetupInfoUserMetrics out of a cgo build constraint

- go.mod
- go.sum
This PR updates the version of the `go-sysinfo` dependency.
The new version of `go-sysinfo` contains a security fix.
> Bump up go-sysinfo dependency version

- metric/system/process/process.go
- metric/system/process/process_aix.go
- metric/system/process/process_darwin.go
- metric/system/process/process_linux_common.go
- metric/system/process/process_test.go
- metric/system/process/process_windows.go
- metric/system/process/process_windows_test.go
It improves metric collection on Windows hosts so we can collect some metrics from privileged process like Elastic Endpoint or Elastic-Agent. In order to achieve that metrics collection for Windows are grouped by the access level required to collect metrics. First the metrics that can be collected with `PROCESS_QUERY_LIMITED_INFORMATION` are collected, then the others are collected. In case the second batch fails, we still report the partial metrics.
It allows us to collect CPU and memory metrics from Endpoint and Elastic-Agent, which improves our monitoring dashboards.
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
- Closes https://github.com/elastic/beats/issues/17314
> Fix metrics collection for privileged process on Windows

- metric/system/cgroup/reader.go
- metric/system/cgroup/util.go
- metric/system/process/process_darwin.go
- metric/system/process/process_linux_common.go
- metric/system/process/process_windows.go
Reduce resource usage by preallocating memory and using caches.
`elastic/elastic-agent-system-metrics` is a direct dependency of beats like `metricbeat`.
As shown in the above screenshot, `metricbeat` spends most of its time in `elastic/elastic-agent-system-metrics` doing syscalls to walk directories.
> reduce resource usage

- .buildkite/hooks/pre-command
- .buildkite/pipeline.yml
- .buildkite/scripts/common.sh
- .buildkite/scripts/run-linux-tests.sh
- catalog-info.yaml
to complete migration to BK (Jenkins job had tests on macos) 
- Relates [#1711](https://github.com/elastic/ingest-dev/issues/1711)
____
windows and MacOS are failing: https://github.com/elastic/elastic-agent-system-metrics/issues/109
> Buildkite: add test on macos

- metric/system/process/process_windows.go
- metric/system/process/syscall_windows.go
- metric/system/process/zsyscall_windows.go
Frees the memory that is allocated when PssCaptureSnapshot is called.
memory leak
- 
- run metricbeat 8.11.0 or 8.11.1 on Windows, notice memory consumption of metricbeat continually climbs
- rebuild metricbeat using this path
- memory consumption rises in first 10min or so, but is steady after that
> add PssFreeSnapshot

- metric/system/diskio/diskstat_windows_helper.go
- metric/system/process/process.go
- metric/system/process/process_darwin.go
- metric/system/process/process_linux_common.go
- metric/system/process/process_windows.go
Whenever possible, preallocate array to the correct size instead of letting arrays "grow". This reduces the load on the Garbage Collector and improves memory usage efficiency.
> metric/system: preallocate arrays

- .github/workflows/golangci-lint.yml
- Fix CI configuration issue - e.g. https://github.com/elastic/elastic-agent-system-metrics/actions/runs/6978945111
```
[Invalid workflow file: .github/workflows/golangci-lint.yml#L57](https://github.com/elastic/elastic-agent-system-metrics/actions/runs/6978945111/workflow)
You have an error in your yaml syntax on line 57
```
- Update CI dependencies like `actions/checkout` and `actions/setup-go` to latest version
- Align golangci-lint version to `v1.55.2`
> CI: fix linter config issue

- .github/workflows/golangci-lint.yml
- .golangci.yml
`skip-go-install` was removed with
https://github.com/golangci/golangci-lint-action/commit/423fbafafc226b312a399e5a5c942041f5d6f24f. As this optional argument is still used in golangci-lint-action, the action fails with:
```
Unexpected input(s) 'skip-go-installation', valid inputs are ['version', 'args', 'working-directory', 'github-token', 'only-new-issues', 'skip-cache', 'skip-pkg-cache', 'skip-build-cache', 'install-mode']
```
https://github.com/elastic/elastic-agent-system-metrics/actions/runs/7017910507/job/19092190110#step:6:1
> CI: remove deprecated skip-go-install option

- CHANGELOG.md
- metric/system/cgroup/cgv1/blkio.go
- metric/system/cgroup/cgv1/blkio_test.go
- metric/system/cgroup/testdata/docker/sys/fs/cgroup/blkio/docker/b29faf21b7eff959f64b4192c34d5d67a707fe8561e9eaa608cb27693fba4242/blkio.throttle.io_service_bytes
- metric/system/cgroup/testdata/docker/sys/fs/cgroup/blkio/docker/b29faf21b7eff959f64b4192c34d5d67a707fe8561e9eaa608cb27693fba4242/blkio.throttle.io_serviced
This PR adds reads and writes metrics for cgroups V1. Currently, only the total of reads and writes is available and this metric alone is not really useful to understand what is happening inside a container.
These metrics are important to understand what is happening inside a container running on Kubernetes or Docker and to attribute reads and writes on a host to running containers.
-
> Add metrics for disk reads and writes per cgroup

- .buildkite/pull-requests.json
also need to allow github-actions bot
_from documentation:
allowed_list
Comma-separated list of users who are able to trigger this job
Value: user1,user2,user3
Default: _
> update bk bot settings

- metric/system/cgroup/cgstats.go
- metric/system/cgroup/doc.go
- metric/system/cgroup/reader.go
- metric/system/cgroup/util.go
- metric/system/filesystem/filesystem.go
- metric/system/host/host_test.go
- metric/system/hwmon/hwmon.go
- metric/system/network/helpers_test.go
Reintroduce the improvements from https://github.com/elastic/elastic-agent-system-metrics/pull/103. This PR got reverted with https://github.com/elastic/elastic-agent-system-metrics/pull/113 because of https://github.com/elastic/elastic-agent-system-metrics/issues/109. The issue, that got reported in https://github.com/elastic/elastic-agent-system-metrics/issues/109, was fixed with https://github.com/elastic/elastic-agent-system-metrics/pull/116.
So its time to bring back the performance improvements by reintroducing the cache for cgroup v2.
> metric/system/cgroup: introduce cache for cgroup v2

- .golangci.yml
- metric/system/process/process_test.go
Fixes an issue that came to light with https://github.com/elastic/elastic-agent-system-metrics/pull/125
In certain instances, `FilterTest` will fail, if the process with the most memory usage and most CPU usage are the same.
> Fix process filter test

- .buildkite/pipeline.yml
- CHANGELOG.md
- metric/system/process/process.go
- metric/system/process/process_linux_common.go
- metric/system/process/process_linux_test.go
This fixes a change in the behavior of the system metrics where fetching process metrics on a container without `SYS_PTRACE` results in a failure, as `/proc/pid/io` requires `SYS_PTRACE`.
This flies under the radar in a handful of use cases, as our docs mention `SYS_PTRACE` in other contexts, and many users monitoring system data will (in my experience) end up passing `--privileged` due to [a variety of issues with permissions in `proc`](https://stackoverflow.com/questions/56573990/access-to-full-proc-in-docker-container). This issue also doesn't appear outside of docker.
There is a test already that does cover this (although it'll catch it for a permissions error, not a container capability error): `TestFetchProcessFromOtherUser`, however, that test is usually skipped in CI, as the CI …
> Make /proc/pid/io lookup failures skippable

- metric/system/process/process_container_test.go
- metric/system/process/process_linux_common.go
- tests/container_system_mon_test.go
Closes https://github.com/elastic/elastic-agent-system-metrics/issues/135
This fixes an issue where our permissions checks for fetching `/proc/pid/exe` could fail for kernel procs and certain docker configs.
Also re-enables one of the tests.
This is a bug that causes data loss.
> Fix exe error checks

- metric/system/process/process.go
- metric/system/process/process_container_test.go
- metric/system/process/process_darwin.go
- metric/system/process/process_linux_common.go
- metric/system/process/process_linux_test.go
- metric/system/process/process_windows.go
Closes https://github.com/elastic/elastic-agent-system-metrics/issues/147
This fixes an issue where `Stats.GetSelf()` would fail when run inside a container while using a hostfs path, as the PID returned by `os.Getpid()` would not be valid outside the container runtime. 
This changes the logic, so if we have a `hostfs` set, `GetSelf` will fetch the pid from `/hostf/proc/self`.
This is a bug.
> Fix GetSelf() logic when running with alternate hostfs

- metric/system/process/process.go
- metric/system/process/process_common.go
- metric/system/process/process_test.go
- metric/system/process/process_types.go
This is part of https://github.com/elastic/elastic-agent/issues/4083 
This adds a `GetOneRootEvent()`. method to `ProcStats` we need this for https://github.com/elastic/elastic-agent/issues/4083 , as that issue requires metricbeat's system/process metricset to monitor a specific PID, which it can't do now. This will have to be followed up with a change to beat itself to rope this in. This also cleans up a bit of code and adds some docs.
needed for https://github.com/elastic/elastic-agent/issues/4083
> Add GetOneRootEvent method to process handler

- metric/system/process/process.go
- metric/system/process/process_common.go
- metric/system/process/process_test.go
This fixes a small bug introduced in #150, where we weren't setting the `ProcState` object while creating the root event.
This is needed for https://github.com/elastic/beats/pull/39620
The previous PR adds fields that weren't in events before, this fixes that.
> Use pointer for processRootevent

- .buildkite/pipeline.yml
The image family `ci-windows-2022` used by the build agent has been unmaintained for a while and has been replaced by `core-windows-2022`. This PR updates them to this instead.
Related to [incident 505.](https://elastic.slack.com/archives/C078RND5G5C)
To mitigate issues from incident 505.](https://elastic.slack.com/archives/C078RND5G5C)
> Use core-windows-2022 instead of unmaintained ci-windows-2022

- metric/system/process/process_darwin.go
The order of arguments in the logger is incorrect. `pid` should be logged first and then the size returned.
> [process][darwin]: fix incorrect logging

- metric/system/process/helpers.go
- metric/system/process/process.go
- Bug
A quick fix PR to move `NonFatalErr` to helpers.go instead of process.go.
This makes sure that `NonFatalErr` compiles for all OS'.
-
> fix: move non-fatal error to helpers

- NOTICE.txt
- go.mod
- go.sum
- metric/system/host/host.go
- metric/system/host/host_test.go
Upgrades go-sysinfo to v1.14.1, which does not lower-case the FQDN. Therefore, `host.name` returned by  `host.MapHostInfo` is lower-cased to comply with [ECS](https://www.elastic.co/guide/en/ecs/current/ecs-host.html#field-host-name).
The FQDN should not be lower-cased by default and the `host.hostname`, when set to FQDN, should be the FQDN as defined in the system.
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- Relates https://github.com/elastic/beats/issues/39993
> Comply with ECS for `host.name`

- metric/system/process/helper_test.go
- metric/system/process/helpers.go
- metric/system/process/helpers_others.go
- metric/system/process/helpers_windows.go
- metric/system/process/process.go
- metric/system/process/process_aix.go
- metric/system/process/process_container_test.go
- metric/system/process/process_darwin.go
- metric/system/process/process_linux_common.go
- metric/system/process/process_test.go
- metric/system/process/process_windows.go
- Previously, we weren't passing errors to the caller while monitoring set of processes.
- With the recent introduction of the status reporter for metricsets, it is impossible to change the status to degraded if such errors are not passed to the caller.
- Fix this by passing errors to the caller. We also populate the process related information to our best-effort.
- See https://github.com/elastic/beats/pull/40400 for testing it on `metricbeat`
**NOTE**: 
- **Only applicable if you're using `system/process` module**
- Non-fatal errors are only received when you have insufficient privileges. 
Steps:
- While receiving any error, test for nature of error
- call `errors.Is(err, NonFatalErr{}))` on received error
- If true, error is non-fatal and you can proceed further (metrics will be …
> [system/process] add support for mutlierr 

- metric/system/cgroup/util.go
This is a one-liner that removes an erroneous `Infof()` debug line that should have been a `Debugf()` line. 
This can create lots of logging noise.
> Change cgroups log line from `Infof` from `Debugf`

- metric/system/process/helpers.go
- metric/system/process/process.go
- metric/system/process/process_linux_test.go
- metric/system/process/process_test.go
So, a previous PR changed the behavior of the process code such that we're now returning non-fatal errors. 
However, a bunch of the tests were not updated, and are now failing. 
I'm a little worried by the fact that none of the tests failed initially, as they fail when I run them locally. Part of the problem is that the CI environment often doesn't have any processes running as other users, meaning we won't hit a lot of code that deals with permissions errors. Still, it feels like _something_ should have failed here. Still investigating. 
This is causing tests here to fail: https://github.com/elastic/beats/pull/40507
> fix non-fatal error tests

- metric/system/process/process_windows.go
- metric/system/process/zsyscall_windows.go
- Enhancement
This PR adds two functions that captures following information for idle process (pid 0). This is the only way I came across as we cannot open process handle for pid 0.
- memory stats
- CPU usage
- number of threads
Future PR:
- In a follow up PR, I'll fix metric collection for PID 4.
- The a final PR to integrate changes and update the final process map to include PID 0 and 4.
- Then, we can merge it to main after testing it thoroughly.
- See https://github.com/elastic/beats/issues/40484 for more info
I've created a dedicated branch called `windows-protected-processes` to hold all the changes. Once we made the necessary updates for protected process, I'll test them manually and then submit a final PR to merge it into the `main` branch. I think this is the best approach to …
> [windows][system/process] - Get Idle process' stats

- metric/system/process/process_windows.go
- Enhancement
We can ignore the error in two cases:
- While reading the process executable name. 
- For pid 4, this call fails as we can't access the executable name via the system call. Same for other kernel-level processes.
- While finding the owner for a particular process.
- We try to open the process token via `syscall.OpenProcessToken`and we can't access the token for protected processes , even as an administrator. 
it's okay to ignore these errors and move forward as we can access few other metrics (memory, cpu).
More context [here](https://github.com/elastic/beats/issues/40484#issuecomment-2400100817)
Relates https://github.com/elastic/beats/issues/40484
> [chore][windows][system/process]: ignore error in some cases

- metric/system/process/process_darwin.go
continue if we encounter an error, or it'll lead to panic here https://github.com/elastic/elastic-agent-system-metrics/blob/ef8d2d0a7e9e0a64a427b190b8c113141f1a99dc/metric/system/process/process_darwin.go#L240-L242
We return an error if we env pairs are invalid. See https://github.com/elastic/elastic-agent-system-metrics/pull/186.
`Continue` if we face error.
> [bugfix][system/process] continue if we encounter an error, or it'll lead to panic

- metric/system/process/process.go
- metric/system/process/process_windows.go
This PR does the following:
- It integrates `getIdleMemory` and `getProcessMemory` introduced in https://github.com/elastic/elastic-agent-system-metrics/pull/181. This is used to capture stats for PID 0.
- `FillMetricsRequiringMoreAccess` adds some extra information about a process. It's failure is expected for protected processes and if a non-root user accesses elevated processes. We can just log the error rather than returning an error. This will not pollute the status message on fleet.
- @cmacknz Please let me know how you feel about this.
This is final PR in this series and once this PR gets merged, we can merge `windows-protected-processes` into `main`.
> [system/process] - Add idle process' stats

- go.mod
- go.sum
- metric/cpu/cpu.go
- metric/cpu/cpu_other.go
- metric/cpu/cpu_windows.go
- metric/cpu/metrics_test.go
This PR is a split from https://github.com/elastic/elastic-agent-system-metrics/pull/192. 
It aims to simplify the query building for performance counters.
Using a global variable might create problems if multiple modules (`cpu` and `core`) are trying to initialise it at a same time.
`sync.Once` adds unnecessary CPU overhead (makes it 4x slower). 
Instead, we can initialise the performance counters in `New(...)` and return error to the caller (i.e. metricbeat).
> [cpu] - Split the initialisation into multiple files

- go.mod
- go.sum
- metric/system/process/helpers.go
- metric/system/process/process.go
- metric/system/process/process_types.go
This is to reduce the log pollution in default case. If the user is interested to view the full log, they can enable "debug" logging.
Closes https://github.com/elastic/beats/issues/41890
> [chore][process] narrow the log that is passed to the caller

- metric/system/process/process.go
- metric/system/process/process_types.go
This PR follows up on https://github.com/elastic/elastic-agent-system-metrics/pull/195 and adds a new boolean to indicate if a given process state is partial. 
This is useful while returning errors to the caller.
> [process] - Add a boolean to detect partial matches

- metric/system/process/helpers_others.go
- metric/system/process/helpers_windows.go
- metric/system/process/process.go
- metric/system/process/process_common.go
- metric/system/process/process_test.go
- metric/system/process/process_windows.go
- metric/system/process/process_windows_test.go
See https://github.com/elastic/beats/issues/41407 for more details.
TL;DR;
Processes such as `lsass.exe` has no meaningful cmd line and and can trigger false positives with Windows ASR rules.
We can find pid for that using `SYSTEM\\CurrentControlSet\\Control\\Lsa` path
Relates https://github.com/elastic/beats/issues/41407
> [process/windows] - Ignore accessing command line arguments for selected processes (currently, lsass.exe)

- report/setup.go
As of now, we use global namespace to create registry and report process and system metrics on that. This PR adds option to specify our custom registry. 
It is intended to be used by beat receivers, so that there is a unique process and system registry under per-beat namespace to avoid conflicts. 
Relates: https://github.com/elastic/ingest-dev/issues/5136
> [monitoring] - add options for specifying registry

- report/setup.go
Use per-namespace registry for platform specific metrics as well.
For some reason, I missed this in https://github.com/elastic/elastic-agent-system-metrics/pull/205 and it wasn't get caught  during reviews as well.
> [registry] use per-namespace registry for platform specific metrics

- metric/system/filesystem/filesystem_unix_common.go
- metric/system/process/process_aix.go
There are two issues in AIX to build elastic-agent-system-metrics.
1: The required build tags needed to build the required Go files. If it's not there then we get function undefined errors.
2: Missing function declaration GetSelfPid().
> FIX  AIX build related issues.
